In [4]:
import pandas as pd

In [29]:
my_data = pd.read_csv("seeds_dataset.txt", sep=r'\s+', header=None).dropna()
my_data

         0      1       2      3      4      5      6  7
0    15.26  14.84  0.8710  5.763  3.312  2.221  5.220  1
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
2    14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1
..     ...    ...     ...    ...    ...    ...    ... ..
205  12.19  13.20  0.8783  5.137  2.981  3.631  4.870  3
206  11.23  12.88  0.8511  5.140  2.795  4.325  5.003  3
207  13.20  13.66  0.8883  5.236  3.232  8.315  5.056  3
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044  3
209  12.30  13.34  0.8684  5.243  2.974  5.637  5.063  3

[210 rows x 8 columns]

In [36]:
my_data.sort_values(by=[0, 1, 2, 3, 4, 5, 6, 7], ascending=[True, True, True, True, True, True, True, False], na_position='first')

         0      1       2      3      4      5      6  7
189  10.59  12.41  0.8648  4.899  2.787  4.975  4.794  3
177  10.74  12.73  0.8329  5.145  2.642  4.702  4.963  3
149  10.79  12.93  0.8107  5.317  2.648  5.462  5.194  3
175  10.80  12.57  0.8590  4.981  2.821  4.773  5.063  3
193  10.82  12.83  0.8256  5.180  2.630  4.853  5.089  3
..     ...    ...     ...    ...    ...    ...    ... ..
120  20.24  16.91  0.8897  6.315  3.962  5.901  6.188  2
77   20.71  17.23  0.8763  6.579  3.814  4.451  6.451  2
89   20.88  17.05  0.9031  6.450  4.032  5.016  6.321  2
114  20.97  17.25  0.8859  6.563  3.991  4.677  6.316  2
88   21.18  17.21  0.8989  6.573  4.033  5.780  6.231  2

[210 rows x 8 columns]